-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: MagicLinkAuthentication.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/magic_link_auth (
  mla_jwt VARCHAR(1000) NOT NULL,
  mla_iv VARCHAR(255) NOT NULL,
  mla_email VARCHAR(255) NOT NULL,
  mla_entropy VARCHAR(255) NOT NULL,
  mla_expiry INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(mla_jwt)
);
